export const  rawBooks= [
  {
    "no": "1 (H03)",
    "id": "dng",
    "kubun": "南北朝写本",
    "name": "S81大般涅槃経巻十一",
    "type": "CM",
    "short_name": "S81",
    "date_order": "506",
    "date": "506",
    "normal_type": "標準",
    "koushi": "",
    "shozo": "BL"
  },
  {
    "no": "2 (H02)",
    "id": "keg",
    "kubun": "南北朝写本",
    "name": "S2067華厳経巻十六",
    "type": "CM",
    "short_name": "S2067",
    "date_order": "513",
    "date": "513",
    "normal_type": "標準",
    "koushi": "公的",
    "shozo": "BL"
  },
  {
    "no": "3 (H01)",
    "id": "jou",
    "kubun": "南北朝写本",
    "name": "P2179誠実論巻八",
    "type": "CM",
    "short_name": "P2179",
    "date_order": "514",
    "date": "514",
    "normal_type": "標準",
    "koushi": "公的",
    "shozo": "BNF"
  },
  {
    "no": "4 (H05)",
    "id": "mam",
    "kubun": "南北朝写本",
    "name": "P2160摩訶摩耶経巻上",
    "type": "CM",
    "short_name": "P2160",
    "date_order": "586",
    "date": "586",
    "normal_type": "標準",
    "koushi": "",
    "shozo": "BNF"
  },
  {
    "no": "5 (H06)",
    "id": "drt",
    "kubun": "隋写本",
    "name": "P2413大楼炭経巻三",
    "type": "CM",
    "short_name": "P2413",
    "date_order": "589",
    "date": "589",
    "normal_type": "標準",
    "koushi": "",
    "shozo": "BNF"
  },
  {
    "no": "6 (H07)",
    "id": "kgk",
    "kubun": "隋写本",
    "name": "賢劫経巻二",
    "type": "CM",
    "short_name": "賢劫経二",
    "date_order": "610",
    "date": "610",
    "normal_type": "",
    "koushi": "私的",
    "shozo": "正倉院"
  },
  {
    "no": "7 (H08)",
    "id": "myz",
    "kubun": "隋写本",
    "name": "P2334妙法蓮華経巻五",
    "type": "CM",
    "short_name": "P2334",
    "date_order": "617",
    "date": "617",
    "normal_type": "標準",
    "koushi": "",
    "shozo": "BNF"
  },
  {
    "no": "8 (H10)",
    "id": "khi",
    "kubun": "初唐写本",
    "name": "今西本妙法蓮華経巻五",
    "type": "CM",
    "short_name": "宮廷今西",
    "date_order": "671",
    "date": "671",
    "normal_type": "標準",
    "koushi": "公的",
    "shozo": "京都国立博物館 "
  },
  {
    "no": "9 (H12)",
    "id": "fhs",
    "kubun": "初唐写本",
    "name": "P2195妙法蓮華経巻六",
    "type": "CM",
    "short_name": "P2195",
    "date_order": "675",
    "date": "675",
    "normal_type": "標準",
    "koushi": "公的",
    "shozo": "BNF"
  },
  {
    "no": "10 (H11)",
    "id": "khm",
    "kubun": "初唐写本",
    "name": "守屋本妙法蓮華経巻三",
    "type": "CM",
    "short_name": "宮廷守屋",
    "date_order": "675",
    "date": "675",
    "normal_type": "標準",
    "koushi": "公的",
    "shozo": "京都国立博物館 "
  },
  {
    "no": "11 (H13)",
    "id": "hok",
    "kubun": "初唐写本",
    "name": "S2577妙法蓮華経巻八",
    "type": "CM",
    "short_name": "S2577",
    "date_order": "690",
    "date": "7C末",
    "normal_type": "",
    "koushi": "私的",
    "shozo": "BL"
  },
  {
    "no": "12 (H14)",
    "id": "kyd",
    "kubun": "初唐写本",
    "name": "上野本漢書揚雄伝",
    "type": "CM",
    "short_name": "漢書揚雄",
    "date_order": "691",
    "date": "初唐",
    "normal_type": "",
    "koushi": "私的",
    "shozo": "個人蔵"
  },
  {
    "no": "13 (H15)",
    "id": "sok",
    "kubun": "則天写本",
    "name": "守屋本花厳経巻八",
    "type": "CM",
    "short_name": "華厳守屋",
    "date_order": "695",
    "date": "則天期",
    "normal_type": "",
    "koushi": "私的",
    "shozo": "京都国立博物館 "
  },
  {
    "no": "14 (H16)",
    "id": "yhk",
    "kubun": "盛唐写本",
    "name": "S2423瑜伽法鏡経",
    "type": "CM",
    "short_name": "S2423",
    "date_order": "712",
    "date": "712",
    "normal_type": "標準",
    "koushi": "",
    "shozo": "BL"
  },
  {
    "no": "15 (H78)",
    "id": "sts",
    "kubun": "盛唐写本",
    "name": "四分律巻第二十",
    "type": "CM",
    "short_name": "正四分20",
    "date_order": "740",
    "date": "740頃",
    "normal_type": "標準",
    "koushi": "",
    "shozo": "正倉院"
  },
  {
    "no": "16 (H70)",
    "id": "saa",
    "kubun": "盛唐写本",
    "name": "阿毘達磨大毘婆沙論巻百七十",
    "type": "CM",
    "short_name": "正毘170",
    "date_order": "800",
    "date": "8C初",
    "normal_type": "",
    "koushi": "私的",
    "shozo": "正倉院"
  },
  {
    "no": "17 (H71)",
    "id": "sab",
    "kubun": "盛唐写本",
    "name": "阿毘達磨大毘婆沙論巻百七十八",
    "type": "CM",
    "short_name": "正毘178",
    "date_order": "801",
    "date": "8C初",
    "normal_type": "",
    "koushi": "私的",
    "shozo": "正倉院"
  },
  {
    "no": "18 (H09)",
    "id": "kda",
    "kubun": "高昌写本",
    "name": "大品経巻二十八",
    "type": "CM",
    "short_name": "京博大品",
    "date_order": "802",
    "date": "高昌期",
    "normal_type": "標準",
    "koushi": "",
    "shozo": "京都国立博物館 "
  },
  {
    "no": "19 (H22)",
    "id": "sys",
    "kubun": "吐蕃写本",
    "name": "S5309瑜伽師地論巻三十",
    "type": "CM",
    "short_name": "S5309",
    "date_order": "857",
    "date": "857",
    "normal_type": "",
    "koushi": "私的",
    "shozo": "BL"
  },
  {
    "no": "20 (H49)",
    "id": "wan",
    "kubun": "大和寧写本",
    "name": "花厳経巻三十八",
    "type": "X",
    "short_name": "和寧花38",
    "date_order": "900",
    "date": "9-10C",
    "normal_type": "標準",
    "koushi": "",
    "shozo": "個人蔵"
  },
  {
    "no": "21 (H72)",
    "id": "wks",
    "kubun": "大和寧写本",
    "name": "守屋本花厳経巻六十七",
    "type": "X",
    "short_name": "和寧花67",
    "date_order": "901",
    "date": "9-10C",
    "normal_type": "標準",
    "koushi": "",
    "shozo": "京都国立博物館 "
  },
  {
    "no": "22 (H73)",
    "id": "wke",
    "kubun": "大和寧写本",
    "name": "守屋本花厳経巻六十八",
    "type": "X",
    "short_name": "和寧花68",
    "date_order": "902",
    "date": "9-10C",
    "normal_type": "標準",
    "koushi": "",
    "shozo": "京都国立博物館 "
  },
  {
    "no": "23 (H81)",
    "id": "wkf",
    "kubun": "大和寧写本",
    "name": "花厳経巻六",
    "type": "X",
    "short_name": "和寧花6",
    "date_order": "903",
    "date": "9-10C",
    "normal_type": "標準",
    "koushi": "",
    "shozo": ""
  },
  {
    "no": "24 (H18)",
    "id": "kar",
    "kubun": "開成石経",
    "name": "開成石経論語",
    "type": "CP",
    "short_name": "開成論語",
    "date_order": "837",
    "date": "837",
    "normal_type": "標準",
    "koushi": "公的",
    "shozo": "東洋文庫"
  },
  {
    "no": "25 (H19)",
    "id": "kae",
    "kubun": "開成石経",
    "name": "開成石経周易",
    "type": "CP",
    "short_name": "開成周易",
    "date_order": "837",
    "date": "837",
    "normal_type": "標準",
    "koushi": "公的",
    "shozo": "東洋文庫"
  },
  {
    "no": "26 (H17)",
    "id": "kak",
    "kubun": "開成石経",
    "name": "開成石経孝経",
    "type": "CP",
    "short_name": "開成孝経",
    "date_order": "837",
    "date": "837",
    "normal_type": "標準",
    "koushi": "公的",
    "shozo": "東洋文庫"
  },
  {
    "no": "27 (H80)",
    "id": "skj",
    "kubun": "北宋版",
    "name": "開宝蔵十誦律巻四十六",
    "type": "CP",
    "short_name": "開宝十誦",
    "date_order": "974",
    "date": "974",
    "normal_type": "標準",
    "koushi": "公的",
    "shozo": "書道博物館"
  },
  {
    "no": "29 (H25)",
    "id": "tzj",
    "kubun": "北宋版",
    "name": "東禅寺版阿毘達磨大毘婆沙論巻百七",
    "type": "CP",
    "short_name": "東禅毘婆",
    "date_order": "1100",
    "date": "1100",
    "normal_type": "標準",
    "koushi": "",
    "shozo": "京都国立博物館"
  },
  {
    "no": "30 (H29)",
    "id": "jhk",
    "kubun": "北宋版",
    "name": "開元寺版道神足無極変化経巻四",
    "type": "CP",
    "short_name": "開元神足",
    "date_order": "1126",
    "date": "1126",
    "normal_type": "標準",
    "koushi": "",
    "shozo": "北海学園大学"
  },
  {
    "no": "31 (H24)",
    "id": "tsu",
    "kubun": "北宋版",
    "name": "通典巻一",
    "type": "CP",
    "short_name": "通典巻一",
    "date_order": "1050",
    "date": "11C",
    "normal_type": "標準",
    "koushi": "",
    "shozo": "書陵部"
  },
  {
    "no": "32 (H26)",
    "id": "hos",
    "kubun": "北宋版",
    "name": "斉民要術",
    "type": "CP",
    "short_name": "斉民要術",
    "date_order": "1100",
    "date": "12C初",
    "normal_type": "",
    "koushi": "私的",
    "shozo": "高山寺"
  },
  {
    "no": "33 (H27)",
    "id": "kkh",
    "kubun": "北宋版",
    "name": "金剛般若経",
    "type": "CP",
    "short_name": "京博金般",
    "date_order": "1101",
    "date": "北宋期か",
    "normal_type": "",
    "koushi": "私的",
    "shozo": "京都国立博物館"
  },
  {
    "no": "34 (H28)",
    "id": "nak",
    "kubun": "南宋版",
    "name": "華厳経内章門等雑孔目巻一",
    "type": "CP",
    "short_name": "華厳孔目",
    "date_order": "1146",
    "date": "1146",
    "normal_type": "標準",
    "koushi": "",
    "shozo": "高山寺"
  },
  {
    "no": "35 (H30)",
    "id": "hod",
    "kubun": "南宋版",
    "name": "法蔵和尚伝",
    "type": "CP",
    "short_name": "法蔵和尚",
    "date_order": "1149",
    "date": "1149",
    "normal_type": "標準",
    "koushi": "",
    "shozo": "高山寺"
  },
  {
    "no": "36 (H31)",
    "id": "gok",
    "kubun": "南宋版",
    "name": "後漢書光武帝紀",
    "type": "CP",
    "short_name": "光武帝紀",
    "date_order": "1198",
    "date": "1198",
    "normal_type": "標準",
    "koushi": "",
    "shozo": ""
  },
  {
    "no": "37 (H74)",
    "id": "smk",
    "kubun": "西夏版",
    "name": "妙法蓮華経巻一",
    "type": "CP",
    "short_name": "西夏法華",
    "date_order": "1149",
    "date": "1149",
    "normal_type": "標準",
    "koushi": "",
    "shozo": "ロシア東方研究所"
  },
  {
    "no": "38 (H50)",
    "id": "okd",
    "kubun": "日本写本",
    "name": "小川本金剛場陀羅尼経",
    "type": "JM",
    "short_name": "金剛小川",
    "date_order": "686",
    "date": "686",
    "normal_type": "標準",
    "koushi": "",
    "shozo": "個人蔵"
  },
  {
    "no": "39 (H54)",
    "id": "wad",
    "kubun": "日本写本",
    "name": "和銅経大般若経巻二百五十",
    "type": "JM",
    "short_name": "和銅250",
    "date_order": "712",
    "date": "712",
    "normal_type": "標準",
    "koushi": "公的",
    "shozo": ""
  },
  {
    "no": "40 (H55)",
    "id": "kmi",
    "kubun": "日本写本",
    "name": "高山寺本弥勒上生経",
    "type": "JM",
    "short_name": "弥勒上生",
    "date_order": "738",
    "date": "738",
    "normal_type": "標準",
    "koushi": "",
    "shozo": "高山寺"
  },
  {
    "no": "41 (H56)",
    "id": "zkd",
    "kubun": "日本写本",
    "name": "守屋本五月一日経続高僧伝",
    "type": "JM",
    "short_name": "五一続高",
    "date_order": "740",
    "date": "740",
    "normal_type": "標準",
    "koushi": "公的",
    "shozo": "京都国立博物館"
  },
  {
    "no": "42 (H77)",
    "id": "sgs",
    "kubun": "日本写本",
    "name": "五月一日経四分律巻十六",
    "type": "JM",
    "short_name": "正四分16",
    "date_order": "741",
    "date": "740頃",
    "normal_type": "標準",
    "koushi": "公的",
    "shozo": "正倉院"
  },
  {
    "no": "43 (H57)",
    "id": "doh",
    "kubun": "日本写本",
    "name": "高山寺本大教王経巻一",
    "type": "JM",
    "short_name": "金剛大教",
    "date_order": "815",
    "date": "815",
    "normal_type": "標準",
    "koushi": "私的",
    "shozo": "高山寺"
  },
  {
    "no": "44 (H79)",
    "id": "kkd",
    "kubun": "日本写本",
    "name": "金剛大教王経巻二",
    "type": "JM",
    "short_name": "院政大教",
    "date_order": "1100",
    "date": "12C初",
    "normal_type": "",
    "koushi": "私的",
    "shozo": "高山寺"
  },
  {
    "no": "45 (H60)",
    "id": "tzs",
    "kubun": "日本写本",
    "name": "東禅寺版写大教王経巻一",
    "type": "JM",
    "short_name": "仏説大教",
    "date_order": "1150",
    "date": "12C",
    "normal_type": "",
    "koushi": "私的",
    "shozo": ""
  },
  {
    "no": "46 (H61)",
    "id": "sai",
    "kubun": "日本写本",
    "name": "東禅寺版写最上秘密那拏天経",
    "type": "JM",
    "short_name": "最上秘密",
    "date_order": "1151",
    "date": "12C",
    "normal_type": "",
    "koushi": "私的",
    "shozo": ""
  },
  {
    "no": "47 (H64)",
    "id": "kss",
    "kubun": "日本写本",
    "name": "明恵自筆華厳信種義",
    "type": "JM",
    "short_name": "華厳信種",
    "date_order": "1221",
    "date": "1221",
    "normal_type": "標準",
    "koushi": "私的",
    "shozo": ""
  },
  {
    "no": "48 (H66)",
    "id": "kyo",
    "kubun": "日本写本",
    "name": "親鸞自筆教行信証巻四",
    "type": "JM",
    "short_name": "教行信証",
    "date_order": "1224",
    "date": "1224",
    "normal_type": "",
    "koushi": "私的",
    "shozo": ""
  },
  {
    "no": "49 (H58)",
    "id": "jyu",
    "kubun": "日本版本",
    "name": "寛治二年刊本成唯識論巻十",
    "type": "JP",
    "short_name": "成唯識10",
    "date_order": "1088",
    "date": "1088",
    "normal_type": "",
    "koushi": "私的",
    "shozo": ""
  },
  {
    "no": "50 (H62)",
    "id": "kad",
    "kubun": "日本版本",
    "name": "春日版大般若経巻八十",
    "type": "JP",
    "short_name": "春日般若",
    "date_order": "1250",
    "date": "13C",
    "normal_type": "標準",
    "koushi": "",
    "shozo": "京都国立博物館"
  },
  {
    "no": "51 (H68)",
    "id": "ykk",
    "kubun": "日本版本",
    "name": "守屋本薬師功徳経",
    "type": "JP",
    "short_name": "薬師功徳",
    "date_order": "1412",
    "date": "1412",
    "normal_type": "",
    "koushi": "私的",
    "shozo": "京都国立博物館"
  },
  {
    "no": "52 (H33)",
    "id": "ink",
    "kubun": "日本書紀写本",
    "name": "岩崎本日本書紀巻二十四",
    "type": "JM",
    "short_name": "岩崎紀24",
    "date_order": "950",
    "date": "10C",
    "normal_type": "",
    "koushi": "私的",
    "shozo": "京都国立博物館"
  },
  {
    "no": "53 (H34)",
    "id": "nto",
    "kubun": "日本書紀写本",
    "name": "図書寮本日本書紀巻二十四",
    "type": "JM",
    "short_name": "図書紀24",
    "date_order": "1142",
    "date": "1142頃",
    "normal_type": "",
    "koushi": "私的",
    "shozo": "書陵部"
  },
  {
    "no": "54 (H38)",
    "id": "ini",
    "kubun": "日本書紀写本",
    "name": "鴨脚本日本書紀巻二",
    "type": "JM",
    "short_name": "鴨脚紀2",
    "date_order": "1236",
    "date": "1236",
    "normal_type": "",
    "koushi": "私的",
    "shozo": ""
  },
  {
    "no": "55 (H39)",
    "id": "nkk",
    "kubun": "日本書紀写本",
    "name": "兼方本日本書紀巻二",
    "type": "JM",
    "short_name": "兼方紀2",
    "date_order": "1286",
    "date": "1286",
    "normal_type": "標準",
    "koushi": "私的",
    "shozo": ""
  },
  {
    "no": "56 (H36)",
    "id": "nkm",
    "kubun": "日本書紀写本",
    "name": "兼右本日本書紀巻二十四",
    "type": "JM",
    "short_name": "兼右紀24",
    "date_order": "1540",
    "date": "1540",
    "normal_type": "",
    "koushi": "私的",
    "shozo": "天理図書館"
  },
  {
    "no": "57 (H41)",
    "id": "kcc",
    "kubun": "日本書紀版本",
    "name": "慶長勅版日本書紀巻二",
    "type": "JP",
    "short_name": "勅版紀2",
    "date_order": "1599",
    "date": "1599",
    "normal_type": "標準",
    "koushi": "公的",
    "shozo": "東洋文庫"
  },
  {
    "no": "58 (H42)",
    "id": "kcj",
    "kubun": "日本書紀版本",
    "name": "慶長十五年版日本書紀巻二",
    "type": "JP",
    "short_name": "慶長紀2",
    "date_order": "1610",
    "date": "1610",
    "normal_type": "",
    "koushi": "私的",
    "shozo": "東洋文庫"
  },
  {
    "no": "59 (H43)",
    "id": "kbk",
    "kubun": "日本書紀版本",
    "name": "寛文九年版日本書紀巻二",
    "type": "JP",
    "short_name": "寛文紀2",
    "date_order": "1669",
    "date": "1669",
    "normal_type": "",
    "koushi": "私的",
    "shozo": "石塚晴通"
  },
  {
    "no": "60 (H37)",
    "id": "k24",
    "kubun": "日本書紀版本",
    "name": "寛文九年版日本書紀巻二十四",
    "type": "JP",
    "short_name": "寛文紀24",
    "date_order": "1669",
    "date": "1669",
    "normal_type": "",
    "koushi": "私的",
    "shozo": "石塚晴通"
  },
  {
    "no": "61 (H44)",
    "id": "sik",
    "kubun": "韓国写本",
    "name": "新羅本花厳経巻八",
    "type": "K",
    "short_name": "華厳新羅",
    "date_order": "754",
    "date": "754-755",
    "normal_type": "標準",
    "koushi": "",
    "shozo": ""
  },
  {
    "no": "62 (H46)",
    "id": "skk",
    "kubun": "韓国印刻本",
    "name": "晋本華厳経巻二十",
    "type": "K",
    "short_name": "古麗華20",
    "date_order": "950",
    "date": "10C",
    "normal_type": "標準",
    "koushi": "私的",
    "shozo": ""
  },
  {
    "no": "63 (H47)",
    "id": "kyu",
    "kubun": "韓国印刻本",
    "name": "高麗初彫本瑜伽師地論巻五",
    "type": "K",
    "short_name": "初麗瑜5",
    "date_order": "1050",
    "date": "11C",
    "normal_type": "標準",
    "koushi": "公的",
    "shozo": ""
  },
  {
    "no": "64 (H48)",
    "id": "ksk",
    "kubun": "韓国印刻本",
    "name": "高麗再彫本華厳経巻六",
    "type": "K",
    "short_name": "再麗華6",
    "date_order": "1250",
    "date": "13C",
    "normal_type": "標準",
    "koushi": "公的",
    "shozo": ""
  }
] as const;